### ISSUE TITLE
Lua 5.1 support

### ISSUE THREAD

**Issue by gfv** [algernon/riemoon#1]
This library can't be built for Lua 5.1, and therefore can't used with LuaJIT. I managed to build it with [lua-compat-5.2](https://github.com/keplerproject/lua-compat-5.2), but in process I had to ditch the whole autotools (which didn't even tell me that it couldn't link the library!) and build it manually.

Is there any way to make it build properly with older Lua?

**Comment by algernon** [comment]
I suppose I can pull in `lua-compat-5.2`, or try making the library compatible with LuaJIT. I will see what I can do, but can't promise anything.

**Comment by algernon** [comment]
Turns out this was very simple. Thanks for the idea!

**Comment by sashman** [comment]
Hey, could you please publish the latest version to LuaRocks. https://luarocks.org/modules/algernon/riemoon seems out of date.

**Comment by algernon** [comment]
Can you please open an issue about that? Would make it a lot easier for me to remember to do so.

Thanks!
