### ISSUE TITLE
Push new version to LuaRocks

### ISSUE THREAD

**Issue by sashman** [algernon/riemoon#2]
Push version 0.0.2 to https://luarocks.org/modules/algernon/riemoon so it's available on LuaRocks

**Comment by sashman** [comment]
Hey @algernon, have you had a chance to have a look at this?

**Comment by algernon** [comment]
Yeah, pushing a new version in a bit. Had to clear up a few things in my queue first.

**Comment by algernon** [comment]
Pushed, thanks for the nudge!

**Comment by sashman** [comment]
Awesome thanks!
